version: "3.2"
services:
  
  appbackend:
    build:
      context: .
      dockerfile: Dockerfile-node
    container_name: backend
    volumes:
      - ./:/usr/src/app
      - ./node_modules:/usr/src/app/node_modules
    ports:
      - 3000:3000
    environment:
      - HOST=172.10.0.10
      - PORT=5432
      - USER=postgres
      - PASSWORD=280510
      - DATABASE=silviopd
      # - HOST=dpg-cg4tkt02qv287cr8ahog-a.oregon-postgres.render.com
      # - PORT=5432
      # - USER=dbtestapi_user
      # - PASSWORD=nSVjtqIX38nDjyLwELnu5kBYVoT6GeLo
      # - DATABASE=dbtestapi
    depends_on:
      - postgres
    command: npm run dev
    networks:
      redTest:
        ipv4_address: 172.10.0.14


  mysql:
    image: mariadb
    container_name: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - $PWD/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=280510
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=silviopd
    ports:
      - "3306:3306"
    networks:
      redTest:
        ipv4_address: 172.10.0.12

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    networks:
      redTest:
        ipv4_address: 172.10.0.13


  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=280510
      - POSTGRES_DB=silviopd
    volumes:
      - $PWD/postgresql/:/var/lib/postgresql
    networks:
      redTest:
        ipv4_address: 172.10.0.10

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      redTest:
        ipv4_address: 172.10.0.11

  # gitlabrunner: 
  #   build:
  #     context: .
  #     dockerfile: Dockerfile-Gitlab-runner
  #   container_name: gitlabrunner
  #   volumes:
  #     - ./gitlab-runner:/etc/gitlab-runner
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   # ports:
  #   #   - 3000:3000
  #   depends_on:
  #     - appbackend
  #   networks:
  #     redTest:
  #       ipv4_address: 172.10.0.15

networks:
  redTest:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/24

